services:
  - type: web
    name: skillconnect-freelancerweb
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate --noinput
      python manage.py collectstatic --noinput
    startCommand: gunicorn SkillConnect.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        value: postgresql://skillconnect_db_user:fMdyCb5aImIE7MEnQfplKVleuCfUhfXY@dpg-d4cpan0dl3ps73bkr3k0-a.oregon-postgres.render.com/skillconnect_db
      - key: SECRET_KEY
        value: "django-insecure-9fd!u!9d+cff^@vv7bfdu2xbr@^8my7t9iocl31sdt-7kc5_66"
      - key: EMAIL_HOST_USER
        value: "nikhillanje555@gmail.com"
      - key: EMAIL_HOST_PASSWORD
        value: "csnt iuqc shsq uaxb"
      - key: GEMINI_API_KEY
        value: "AIzaSyCT2txD_Amkwxu0aRwK51ljFSt7vgGA_QU"