services:
  - type: web
    name: skillconnect-freelancerweb
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput"
    startCommand: "gunicorn SkillConnect.wsgi"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: SkillConnect.settings
